spring:
  application:
    name: siclo-reservations-api
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      jdbc:
        batch_size: 100
        batch_versioned_data: true
      order_inserts: true
      order_updates: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  secret: ${jwt.secret}
  expiration: 86400000 # 24 hours in ms

auth:
  jwt:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /siclo/api